server:
  port: 8888

spring:
#  mysql
  datasource:
    username: root
    password: 1178055813
    url: jdbc:mysql://localhost:3306/starter?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
#  redis
  redis:
    database: 0
    host: 8.140.153.233
    port: 6379
    timeout: 15000
    lettuce:
      pool:
        max-active: 1000
        max-idle: 100
        max-wait: -1ms
#   mybatis
mybatis:
  type-aliases-package: com.lbh.starter.pojo
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true

mybatis-plus:
  type-enums-package: com.lbh.starter.enmus

## redis 属性信息
### redis数据库索引（默认为0）
#spring.redis.database=0
### redis服务器地址
#spring.redis.host=localhost
### redis服务器连接端口
#spring.redis.port=6379
### redis服务器连接密码（默认为空）
#spring.redis.password=123456
### 连接池最大连接数（使用负值表示没有限制）
#spring.redis.jedis.pool.max-active=8
### 连接池中的最大空闲连接
#spring.redis.jedis.pool.max-idle=8
### 连接池最大阻塞等待时间（使用负值表示没有限制）
#spring.redis.jedis.pool.max-wait=-1ms
### 连接池中的最小空闲连接
#spring.redis.jedis.pool.min-idle=0
